### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by wottpal** [JustinAiken/alfred-atom-projects#1]
I am sorry, I downloaded this repository this the `bundle install` (everything went fine) but where is the workflow now? How to install it to Alfred? Does it appear automatically in the workflow-list or don't I need an `.alfredworkflow`-file?

Dennis

**Comment by JustinAiken** [comment]
> don't I need an .alfredworkflow-file?

Yep! It's on the github [releases](https://github.com/JustinAiken/alfred-atom-projects/releases) page.

**Comment by JustinAiken** [comment]
[Added](https://github.com/JustinAiken/alfred-atom-projects/commit/d164f76dc35a882f0aef6a2187f4480b6bc5f191) a note on that to the install instructions to make it more clear
